# if you are looking for user parameters, please refer to config.yaml
# only touch this if working on Octavius internals please

ptypes: [gas, star, dm, bh]
baryonic_ptypes: [gas, star, bh]
groups: [haloes, galaxies]

group_types:
  haloes:
    key: HaloID
    kind: halo
    ptypes: [gas, star, dm, bh]
    hdf5_group: halo_data
  galaxies:
    key: GalID
    kind: galaxy
    ptypes: [gas, star, bh]
    hdf5_group: galaxy_data

# aggregate properties stage dependency graph

stages:

  find_galaxies:  # only declared so galaxy finding can use the autoloader (doesn't write outputs)
    label: fof6d
    applies_to: []
    requires: []
    needs_particle_columns:
      gas: [pos, vel, rho, sfr, metallicity, helium_fraction, temperature]
      star: [pos, vel]
      bh: [pos, vel]

  properties_core:
    label: core
    applies_to: [haloes, galaxies]
    requires: []
    needs_particle_columns:
      all: [pos, vel, mass, potential]
    outputs:
      - columns: ["n_{ptype}", "mass_{ptype}"]
        over: {ptype: [gas, star, dm, bh]}
      - columns: ["L_{ptype}", "velocity_dispersion_{ptype}", "L_azimuth_{ptype}", "L_elevation_{ptype}", "inertia_tensor_{ptype}", "radius_max_{ptype}"]
        over: {ptype: [gas, star, dm, bh]}
      - columns: ["BoverT_{ptype}", "kappa_rot_{ptype}"]
        over: {ptype: [gas, star, bh]}
        applies_to: [galaxies]
      - columns: ["mass_{combined}", "L_{combined}", "velocity_dispersion_{combined}", "L_azimuth_{combined}", "L_elevation_{combined}", "inertia_tensor_{combined}", "radius_max_{combined}"]
        over: {combined: [total, baryon]}
      - columns: ["com_pos_{combined}", "com_vel_{combined}"]
        over: {combined: [total, baryon]}
      - columns: ["BoverT_{combined}", "kappa_rot_{combined}"]
        over: {combined: [baryon]}
        applies_to: [galaxies]
      - columns: ["minpot_pos", "minpot_vel"]
        applies_to: [haloes]
      - columns: ["radius_{quantile}_{ptype}"]
        over:
          ptype: [gas, star, dm, bh, total, baryon]
          quantile: from_config:radial_quantiles
      - columns: ["r{factor}c", "m{factor}c"]
        over: {factor: from_config:virial_factors}
        applies_to: [haloes]
      - columns: ["r200m", "temperature_virial", "velocity_circular", "spin_param", "vmax", "rmax"]
        applies_to: [haloes]

  properties_ptype_specific:
    label: particle_specific
    applies_to: [haloes, galaxies]
    requires: []
    needs_particle_columns:
      all: [mass]
      gas: [metallicity, sfr, rho, mass_HI, mass_H2, helium_fraction, temperature]
      star: [metallicity, age]
      bh: [bhmass, bhmdot]
    outputs:
      - columns: ["mass_HI", "mass_H2", "sfr", "metallicity_gas_mass_weighted", "metallicity_gas_sfr_weighted", "temperature_gas_mass_weighted", "mass_gas_cold", "mass_gas_hot"]
      - columns: ["metallicity_gas_mass_weighted_cgm", "metallicity_gas_temperature_weighted_cgm", "temperature_gas_mass_weighted_cgm", "temperature_gas_metal_weighted_cgm", "mass_cgm"]
        applies_to: [haloes]
      - columns: ["metallicity_star_mass_weighted", "age_star_mass_weighted", "age_star_metal_weighted"]
      - columns: ["smbh_mass", "smbh_mdot", "smbh_fedd"]

  properties_local_environment:
    label: environment
    applies_to: [galaxies]
    requires: [properties_core]  # needs centre of mass
    cross_group_requirements:
      galaxies: [haloes]
    needs_particle_columns: 
      all: [pos, mass]
      gas: [mass_HI, mass_H2]
    outputs:
      - columns: ["mass_{ptype}_{aperture}kpc"]
        over:
          ptype: [gas, star, dm, bh, HI, H2, total]
          aperture: from_config:aperture_size

  photometry:
    label: photometry
    applies_to: [galaxies]
    requires: [properties_ptype_specific, properties_core]  # needs the sfr and metallicity + centre of mass
    cross_group_requirements:
      galaxies: [haloes]
    needs_particle_columns: 
      star: [pos, vel, mass, age, metallicity]
      gas: [pos, mass, metallicity, smoothing_length]
    optional_particle_columns:
      gas: [dust_mass]
    outputs:
      - columns: ["mag_abs_{band}", "mag_abs_nodust_{band}", "mag_app_{band}", "mag_app_nodust_{band}"]
        over: {band: from_config:bands}  # helper methods exist to make this work (see photometry_tables.py)
      - columns: ["luminosity_fir", "beta", "beta_nodust"]


# output column conventions
# stamped onto HDF5 arrays on the output catalogue
# enforces dtypes, units, and provides descriptors

output_columns:

  n_{ptype}:
    over:        {ptype: [gas, star, dm, bh]}
    dtype:       int64
    unit:        ""
    a_exp:       0
    description: "Number of (ptype) particles."

  mass_{ptype}:
    over:        {ptype: [gas, star, dm, bh, total, baryon]}
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "Total (ptype) mass."

  mass_HI:
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "Neutral atomic hydrogen mass."

  mass_H2:
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "Molecular hydrogen mass."

  minpot_pos:
    dtype:       float64
    unit:        "kpc"
    a_exp:       1
    description: "Position vector of the particle at the (halo) minimum potential."

  minpot_vel:
    dtype:       float64
    unit:        "km/s"
    a_exp:       0
    description: "Velocity vector of the particle at the (halo) minimum potential."

  "com_pos_{ptype}":
    over:        {ptype: [total, baryon]}
    dtype:       float64
    unit:        "kpc"
    a_exp:       1
    description: "Position vector of the centre-of-mass."

  "com_vel_{ptype}":
    over:        {ptype: [total, baryon]}
    dtype:       float64
    unit:        "km/s"
    a_exp:       0
    description: "Velocity vector of the centre-of-mass."

  "L_{ptype}":
    over:        {ptype: [gas, star, dm, bh, total, baryon]}
    dtype:       float64
    unit:        "Msun*kpc*km/s"
    a_exp:       1
    description: "Angular momentum vector."

  velocity_dispersion_{ptype}:
    over:        {ptype: [gas, star, dm, bh, total, baryon]}
    dtype:       float64
    unit:        "km/s"
    a_exp:       0
    description: "Mass-weighted (ptype) 3D velocity dispersion."

  L_azimuth_{ptype}:
    over:        {ptype: [gas, star, dm, bh, total, baryon]}
    dtype:       float64
    unit:        "rad"
    a_exp:       0
    description: "Azimuthal angular momentum angle (phi)."

  L_elevation_{ptype}:
    over:        {ptype: [gas, star, dm, bh, total, baryon]}
    dtype:       float64
    unit:        "rad"
    a_exp:       0
    description: "Elevation angular momentum angle (theta)."

  inertia_tensor_{ptype}:
    over:         {ptype: [gas, star, dm, bh, total, baryon]}
    dtype:        float64
    unit:         "Msun*kpc**2"
    a_exp:        2
    description:  "Moment of inertia tensor."

  BoverT_{ptype}:
    over:        {ptype: [gas, star, bh, baryon]}
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "Bulge-to-total (ptype) mass ratio; the bulge mass is kinematically defined as twice the mass which is rotating contrary to the bulk motion."

  kappa_rot_{ptype}:
    over:        {ptype: [gas, star, bh, baryon]}
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "Ratio of (ptype) rotational KE to total KE (rotational support parameter, Sales et al. (2012))."

  "radius_{quantile}_{ptype}":
    over:        {ptype: [gas, star, dm, bh, total, baryon], quantile: from_config:radial_quantiles}
    dtype:       float64
    unit:        "kpc"
    a_exp:       1
    description: "Radius which encloses the fraction (in the quantile) of the (ptype) mass."

  "radius_max_{ptype}":
    over:        {ptype: [gas, star, dm, bh, total, baryon]}
    dtype:       float64
    unit:        "kpc"
    a_exp:       1
    description: "Maximum radius a particle lives at from the centre."

  # only haloes
  vmax:
    dtype:       float64
    unit:        "km/s"
    a_exp:       0
    description: "Maximum circular velocity."

  rmax:
    dtype:       float64
    unit:        "kpc"
    a_exp:       1
    description: "Radius at which vmax occurs."

  r200m:
    dtype:       float64
    unit:        "kpc"
    a_exp:       1
    description: "Virial radius (200x mean matter density)."

  "r{factor}c":
    over:        {factor: from_config:virial_factors}
    dtype:       float64
    unit:        "kpc"
    a_exp:       1
    description: "Radius enclosing {factor}x critical density."

  "m{factor}c":
    over: {factor: from_config:virial_factors}
    dtype: float64
    unit: "Msun"
    a_exp:       0
    description: "Mass enclosed within r{factor}c."

  velocity_circular:
    dtype:       float64
    unit:        "km/s"
    a_exp:       0
    description: "Circular velocity at r200m."

  spin_param:
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "Spin parameter (Bullock) (uses r200m)."

  temperature_virial:
    dtype:       float64
    unit:        "K"
    a_exp:       0
    description: "Virial temperature (uses r200m)."
  # end only haloes

  # only gas
  sfr:
    dtype:       float64
    unit:        "Msun/yr"
    a_exp:       0
    description: "Total star formation rate."

  metallicity_gas_mass_weighted:
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "Mass-weighted gas metallicity."

  metallicity_gas_sfr_weighted:
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "SFR-weighted gas metallicity."

  metallicity_gas_mass_weighted_cgm: # only haloes
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "Mass-weighted CGM gas metallicity."

  metallicity_gas_temperature_weighted_cgm: # only haloes
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "Temperature-weighted CGM gas metallicity."

  temperature_gas_mass_weighted:
    dtype:       float64
    unit:        "K"
    a_exp:       0
    description: "Mass-weighted gas temperature."

  temperature_gas_mass_weighted_cgm: # only haloes
    dtype:       float64
    unit:        "K"
    a_exp:       0
    description: "Mass-weighted CGM gas temperature."

  temperature_gas_metal_weighted_cgm: # only haloes
    dtype:       float64
    unit:        "K"
    a_exp:       0
    description: "Metallicity-weighted CGM gas temperature."

  mass_cgm:  # only haloes
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "CGM gas mass."

  mass_gas_cold:
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "Cold gas mass (as defined in user config Tlim)."

  mass_gas_hot:
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "Hot gas mass (as defined in user config Tlim)."
  # end only gas

  # only stars
  metallicity_star_mass_weighted:
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "Mass-weighted stellar metallicity."

  age_star_mass_weighted:
    dtype:       float64
    unit:        "Gyr"
    a_exp:       0
    description: "Mass-weighted stellar age."

  age_star_metal_weighted:
    dtype:       float64
    unit:        "Gyr"
    a_exp:       0
    description: "Metallicity-weighted stellar age."
  # end only stars

  # only black holes
  smbh_mdot:
    dtype:       float64
    unit:        "Msun/yr"
    a_exp:       0
    description: "Accretion rate of the most massive BH."

  smbh_fedd:
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "Eddington fraction of the most massive BH."

  smbh_mass:
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "Mass of the most massive black hole."

  # end only black holes

  "mass_{ptype}_{aperture}kpc":
    over:        {ptype: [gas, star, dm, bh], aperture: from_config:aperture_size}
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "Mass within the specified kpc aperture."

  mass_HI_{aperture}kpc:
    over: {aperture: from_config:aperture_size}
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "HI mass within the specified kpc aperture."

  mass_H2_{aperture}kpc:
    over: {aperture: from_config:aperture_size}
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "H2 mass within the specified kpc aperture."

  mass_total_{aperture}kpc:
    over: {aperture: from_config:aperture_size}
    dtype:       float64
    unit:        "Msun"
    a_exp:       0
    description: "Total mass within the specified kpc aperture."

  "mag_abs_{band}":
    over:        {band: from_config:bands}
    dtype:       float64
    unit:        "mag"
    a_exp:       0
    description: "Dust-attenuated absolute AB magnitude."

  "mag_abs_nodust_{band}":
    over:        {band: from_config:bands}
    dtype:       float64
    unit:        "mag"
    a_exp:       0
    description: "Absolute AB magnitude (no dust attenuation)."

  "mag_app_{band}":
    over:        {band: from_config:bands}
    dtype:       float64
    unit:        "mag"
    a_exp:       0
    description: "Dust-attenuated apparent AB magnitude."

  "mag_app_nodust_{band}":
    over:        {band: from_config:bands}
    dtype:       float64
    unit:        "mag"
    a_exp:       0
    description: "Apparent AB magnitude (no dust attenuation)."

  "luminosity_fir":
    dtype:       float64
    unit:        "Lsun"
    a_exp:       0
    description: "Bolometric dust-reprocessed luminosity."

  beta:
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "Dust-attenuated UV spectral slope."

  beta_nodust:
    dtype:       float64
    unit:        ""
    a_exp:       0
    description: "UV spectral slope (no dust attenutation)."


membership_columns:

  haloes:
    parent_halo_index:
      dtype: int64
      description: "Catalogue index into halo_data of immediate parent (sub)halo (-1 for field haloes)."
      unit: ""
      a_exp:       0
    field_halo_index:
      dtype: int64
      description: "Catalogue index into halo_data of field halo (-1 for field haloes)."
      unit: ""
      a_exp:       0
    depth:
      dtype: int64
      description: "Depth in the hierarchy from the field halo (0 for field haloes)."
      unit: ""
      a_exp:       0
    central_galaxy_index:
      dtype: int64
      description: "Catalogue index into galaxy_data of most massive galaxy in halo (inclusive of substructure, -1 if no galaxy)."
      unit: ""
      a_exp:       0
    original_ids:
      dtype: int64
      description: "Original halo catalogue IDs (-1 for snapshot-assigned haloes)."
      unit: ""
      a_exp: 0

  galaxies:
    field_halo_index: 
      dtype: int64
      description: "Catalogue index into halo_data of galaxy's field halo."
      unit: ""
      a_exp:       0
    parent_halo_index: 
      dtype: int64
      description: "Catalogue index into halo_data of immediate parent (sub)halo (equal to field_halo_index if no subhalo info); parent decided by plurality."
      unit: ""
      a_exp:       0
    parent_membership_fraction:
      dtype: float32
      description: "Fraction of galaxy's subhalo-assigned particles belonging to the halo at parent_halo_index."
      unit: ""
      a_exp:       0

header_fields:

  boxsize:
    unit: "kpc"
    a_exp: 1
    description: "Length of the box; this is always cubic, so V = boxsize**3"
  h:
    unit: ""
    a_exp: 0
    description: "Reduced Hubble constant."
  scale_factor:
    unit: ""
    a_exp: 0
    description: "Scale factor at this redshift."
  redshift:
    unit: ""
    a_exp: 0
    description: "Redshift of the snapshot."
  omega_matter:
    unit: ""
    a_exp: 0
    description: "Dimensionless mean matter density at z = 0."
  omega_lambda:
    unit: ""
    a_exp: 0
    description: "Dimensionless mean dark energy density at z = 0."
  w_0:
    unit: ""
    a_exp: 0
    description: "Value of the dark energy EoS parameter at z = 0."
  w_a:
    unit: ""
    a_exp: 0 
    description: "Temporal evolution of the dark energy EoS."
  mis:
    unit: "kpc"
    a_exp: 1
    description: "Mean baryonic interparticle separation."
  time_gyr:
    unit: "Gyr"
    a_exp: 0
    description: "Age of the universe at this redshift."
  Hz:
    unit: "km/s/Mpc"
    a_exp: 0
    description: "Hubble constant at this redshift."
  rhocrit:
    unit: "Msun/kpc**3"
    a_exp: 0
    description: "Critical density of the Universe at this redshift."
  r200_factor:
    unit: "kpc/Msun**1/3"
    a_exp: 0
    description: "r200m prefactor."
  